Docker/Docker.py, Docker/README.md
@carlosperello @jsoucheiron small change to allow people to choose which command goes to ```docker ps```
=> make -a -l options

ZooKeeper/ZooKeeper.py
=> Fixed 'port' config reference

HAProxyPro/HAProxyPro.py, HAProxyPro/README.md
From https://github.com/rex/sd-haproxy
tested & works fine
=> Haproxypro

NginxPlus/NginxPlus.py
Changing agentConfig to rawConfig.
=> agentConfig is for internal use only, rawConfig for plugin config

HAProxyPro/HAProxyPro.py
Complete the rename from `HaProxyPro` to `HAProxyPro` done in #41 
n/a
n/a
n/a
n/a
n/a
=> Complete HAProxyPro fix

Uwsgi/README.md, Uwsgi/Uwsgi.py
Parse uWSGI stats server json and output a flatified version of the
stats.
=> Implement uWSGI plugin

Redis/README.md, Redis/Redis.py
- Authentification
- Fix TypeError and ValueError exceptions
- Update documention
=> Add authentification for Redis instance

Redis/README.md, Redis/Redis.py
- Queue length metrics
- Update documentation
=> Add queue length metrics

RunningProcesses/README.md, RunningProcesses/RunningProcesses.py
A plugin for checking whether one or more named processes exist.
=> Add RunningProcesses plugin

Mdadm/Mdadm.py, Mdadm/README.md
=> Plugin to check mdadm status

Mdadm/Mdadm.py, Mdadm/README.md
Updated to return either 1 or 0 for md*_degraded. Also updated readme.
@harryperks can you review please?
=> Remove mdadm string metrics

Mdadm/Mdadm.py
Self is a reference to the class and will only work inside the class.
Moved check to inside of the class to allow plugin to work.
@harryperks can you review please?
=> Moved import check

Mdadm/README.md
@harryperks can you review this please?
=> Added install instructions for v2 agent

MountPoints/MountPoints.py, MountPoints/README.md
This plugin gathers all mount points and reports them back as a string.
@harryperks can you review please?
=> Mount Point plugin

Docker/README.md, Mongodb/README.md, MySQL/readme.md, Redis/README.md
Added deprecation notice to docker, mongodb, mysql and redis readme’s
@harryperks can you review and merge please?
=> Add deprecation notice

.travis.yml, Foocast/Foocast.py, Foocast/README.md, Foocast/datacenters.yaml, Foocast/datacenters_full.yaml, Icinga2/Icinga.py, Icinga2/README.md, Nagios/Nagios.py, Nagios/README.md, RDS/README.md
Merges the Icinga2, Nagios and Foocast plugins from Bencer into sd-agent-plugins.
The travis line limit has been raised to 100 too.
Also some small pep8 fixes, and a fix to prevent the plugins from killing the agent if they hit an error.
=> Nagios plugin

NagiosWrapper/README.md
Adds a note to the Nagios wrapper docs to to confirm icinga2 plugin compatibility.
=> Add note about icinga2 compatibility

NagiosWrapper/NagiosWrapper.py, NagiosWrapper/README.md
Refactoring of the code to implement scheduled runs of Nagios plugins.
@shurl could you review it?
=> Nagios delayed check

NagiosWrapper/README.md
Just a tiny doc update to clarify crontab dependency installation
@carlosperello
=> A quick doc change for clarity that focus requested.

NetworkInterface/NetworkInterface.py, NetworkInterface/README.md
This PR adds a Network Interface plugin to check the status of Network Interfaces. 
@NassimHC please can you review and merge if happy?
=> Add NetworkInterface plugin
